While developing the app, I want to check how the dataframes look like and test small scripts; I will do it on here!

In [ ]:
import pandas as pd

ticker = "EURUSD=X"
desc = "complete"

pred_data = pd.read_parquet(f"../data/prediction_data/{ticker}_predictions_data_{desc}").sort_values(by='date', ascending=False)

,date,high_pred,low_pred,sentiment_polarity_pred,open_pred,close_pred,sentiment_polarity_sma_pred,high_sma_pred,low_sma_pred,open_sma_pred,close_sma_pred,sent_pred
7,2025-04-15,0.907466,0.898094,0.728575,0.900937,0.901308,0.682782,0.908903,0.901947,0.905727,0.905731,None
6,2025-04-14,0.908670,0.900406,0.719408,0.903587,0.903939,0.685482,0.910321,0.903369,0.907143,0.907148,None
5,2025-04-13,0.909352,0.900208,0.723428,0.904292,0.904625,0.685947,0.911330,0.904353,0.908212,0.908219,None
4,2025-04-12,0.900428,0.892085,0.760622,0.903077,0.903239,0.693966,0.910587,0.903744,0.907415,0.907509,None
3,2025-04-11,0.902387,0.893975,0.756818,0.904119,0.904284,0.693376,0.911991,0.905147,0.908847,0.908930,None
2,2025-04-10,0.911534,0.902897,0.706580,0.906406,0.906696,0.685633,0.914834,0.907895,0.911755,0.911752,None
1,2025-04-09,0.912623,0.903709,0.687794,0.907526,0.907786,0.684874,0.915984,0.909096,0.912918,0.912919,None
0,2025-04-08,0.912946,0.903994,0.726804,0.907276,0.907522,0.686044,0.917133,0.910290,0.914084,0.914087,None

In [30]:
from datetime import datetime

today = datetime.today().date()
print(today)

2025-04-09

In [20]:
import pandas as pd

ticker = "EURUSD=X"
desc = "complete"

err_data = pd.read_parquet(f"../data/error_data/{ticker}_error_data_{desc}").sort_values(by='date', ascending=False)

print(err_data.iloc[0,-2])
print(err_data.iloc[0,-1])
err_data

1.1058276891708374
1.0957703590393066

,date,high_pred,low_pred,sentiment_polarity_pred,open_pred,close_pred,sentiment_polarity_sma_pred,high_sma_pred,low_sma_pred,open_sma_pred,close_sma_pred,high_real,low_real
1,2025-04-09,0.912623,0.903709,0.687794,0.907526,0.907786,0.684874,0.915984,0.909096,0.912918,0.912919,1.105828,1.095770
0,2025-04-08,0.912946,0.903994,0.726804,0.907276,0.907522,0.686044,0.917133,0.910290,0.914084,0.914087,0.918156,0.909786

In [7]:
import pandas as pd

ticker = "EURUSD=X"
desc = "complete"

pd.read_parquet(f"../data/modelling_dataset/{ticker}_modelling_dataset").sort_values(by='date', ascending=False)

,date,sentiment_polarity,High,Low,Open,Close,sentiment_polarity_sma,High_sma,Low_sma,Open_sma,Close_sma
125,2025-04-08,0.671861,0.918156,0.909786,0.916238,0.916238,0.705014,0.923308,0.916151,0.919993,0.920001
124,2025-04-07,0.734600,0.917263,0.904986,0.910531,0.910531,0.704579,0.923541,0.916408,0.920315,0.920323
123,2025-04-04,0.691375,0.912101,0.900406,0.905387,0.905551,0.703041,0.923950,0.917148,0.920830,0.920838
122,2025-04-03,0.758440,0.919050,0.898457,0.917011,0.917011,0.706635,0.924722,0.918060,0.921916,0.921916
121,2025-04-02,0.781711,0.927498,0.919760,0.926381,0.926381,0.696653,0.925143,0.919217,0.922388,0.922388
...,...,...,...,...,...,...,...,...,...,...,...
8,2024-10-21,0.730683,0.924300,0.920107,0.920141,0.920141,0.687068,0.922346,0.918861,0.920019,0.920019
7,2024-10-18,0.663025,0.923702,0.920539,0.923480,0.923480,0.679634,0.920889,0.917714,0.919093,0.919093
6,2024-10-17,0.712921,0.924907,0.920209,0.920955,0.920955,0.649957,0.919180,0.916194,0.917322,0.917322
5,2024-10-16,0.582101,0.920133,0.917372,0.918814,0.918814,0.643575,0.917455,0.914754,0.915925,0.915925
4,2024-10-15,0.746610,0.918687,0.916078,0.916708,0.916708,0.682344,0.916247,0.913455,0.914393,0.914393

In [2]:
import pandas as pd 

pd.read_parquet(r"C:\Users\sumag\Downloads\EURUSD=X_modelling_dataset")

,date,sentiment_polarity,High,Low,Open,Close,sentiment_polarity_sma,High_sma,Low_sma,Open_sma,Close_sma
125,2025-04-08,0.671861,0.918156,0.909786,0.916238,0.916238,0.705014,0.923308,0.916151,0.919993,0.920001
124,2025-04-07,0.734600,0.917263,0.904986,0.910531,0.910531,0.704579,0.923541,0.916408,0.920315,0.920323
123,2025-04-04,0.691375,0.912101,0.900406,0.905387,0.905551,0.703041,0.923950,0.917148,0.920830,0.920838
122,2025-04-03,0.758440,0.919050,0.898457,0.917011,0.917011,0.706635,0.924722,0.918060,0.921916,0.921916
121,2025-04-02,0.781711,0.927498,0.919760,0.926381,0.926381,0.696653,0.925143,0.919217,0.922388,0.922388
...,...,...,...,...,...,...,...,...,...,...,...
8,2024-10-21,0.730683,0.924300,0.920107,0.920141,0.920141,0.687068,0.922346,0.918861,0.920019,0.920019
7,2024-10-18,0.663025,0.923702,0.920539,0.923480,0.923480,0.679634,0.920889,0.917714,0.919093,0.919093
6,2024-10-17,0.712921,0.924907,0.920209,0.920955,0.920955,0.649957,0.919180,0.916194,0.917322,0.917322
5,2024-10-16,0.582101,0.920133,0.917372,0.918814,0.918814,0.643575,0.917455,0.914754,0.915925,0.915925
4,2024-10-15,0.746610,0.918687,0.916078,0.916708,0.916708,0.682344,0.916247,0.913455,0.914393,0.914393